# Incluir las reglas base recomendadas por Flutter
include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint

  errors:
    # ⚠️ Se ignoran algunas reglas que pueden ser demasiado estrictas o incompatibles con el estilo del proyecto

    # Permitir el uso de comillas dobles en lugar de simples
    prefer_single_quotes: ignore

    # Permitir constantes con nombres que no siguen el estilo UPPER_SNAKE_CASE
    constant_identifier_names: ignore

    # Permitir anotaciones en ubicaciones no estándar (útil para freezed, json_serializable, etc.)
    invalid_annotation_target: ignore

    # Evitar uso de BuildContext después de await
    use_build_context_synchronously: ignore

    # Permitir uso de miembros protegidos (útil en mixins o librerías internas)
    invalid_use_of_protected_member: ignore
    depend_on_referenced_packages: ignore
    file_names: ignore

linter:
  rules:
    # ✅ Buenas prácticas con 'const'
    prefer_const_literals_to_create_immutables: true
    prefer_const_constructors_in_immutables: true
    unnecessary_const: true
    prefer_const_constructors: true

    # ✅ Organización y estilo
    sort_constructors_first: true

    # ⚠️ Import absoluto permitido
    prefer_relative_imports: false

    # Otras reglas opcionales
    prefer_single_quotes: true

dart_code_metrics:
  extends:
    - recommended
  rules:
    avoid-inferrable-type-arguments: false
    avoid-undisposed-instances: false
    avoid-shadowing: false
